/** Variación de tamaño/precio (ej. Media 7.50, Completa 12) */
export interface MenuItemVariation {
  name: string;
  price: number;
}

/** Grupo de complementos (ej. "Elige tu arroz" con opciones Moro, Blanco) */
export interface MenuItemComplementGroup {
  groupLabel: string;
  options: string[];
}

export interface MenuItem {
  id: string;
  name: string;
  price: number;
  description?: string;
  image?: string;
  bestseller?: boolean;
  category: string;
  /** Si true, se muestran variaciones y se usa su precio en lugar del base */
  tieneVariaciones?: boolean;
  variaciones?: MenuItemVariation[];
  /** Si true, el cliente debe elegir una opción por cada grupo */
  tieneComplementos?: boolean;
  complementos?: MenuItemComplementGroup[];
}

export interface Review {
  author: string;
  rating: number;
  comment: string;
}

export interface TransferenciaLocal {
  numeroCuenta: string;
  cooperativa: string;
  titular?: string;
  tipoCuenta?: string;
  codigoBase64?: string;
  codigoMimeType?: string;
}

export type HorarioItem = { dia: string; abierto: boolean; desde: string; hasta: string };

export interface Local {
  id: string;
  name: string;
  rating: number;
  reviews: number;
  time: string;
  shipping: number;
  type: string[];
  distance: string;
  destacado: boolean;
  /** Local destacado (monetización). Refleja el campo Firestore isFeatured. */
  isFeatured?: boolean;
  /** Timestamp (ms) opcional hasta cuándo se mantiene el destacado. */
  featuredUntil?: number | null;
  logo: string;
  cover: string;
  address?: string;
  /** Coordenadas del local para cálculo de distancia. */
  lat?: number;
  lng?: number;
  minOrder?: number;
  categories: string[];
  transferencia?: TransferenciaLocal;
  status?: 'active' | 'suspended';
  telefono?: string;
  horarios?: HorarioItem[];
  /** ISO date string: hasta cuándo no recibir pedidos (ocupado). */
  cerradoHasta?: string;
  /** Registro interno (solo maestro): nombre, teléfono y correo del dueño. */
  ownerName?: string;
  ownerPhone?: string;
  ownerEmail?: string;
  /** ISO date: desde cuándo se cobran comisiones a este local (por defecto programStartDate o fecha creación). */
  commissionStartDate?: string;
}

export const locales: Local[] = [
  {
    id: 'rhk',
    name: 'RHK Asadero Restaurant',
    rating: 4.8,
    reviews: 120,
    time: '25-35 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '1.2 km',
    destacado: true,
    logo: '/logos/rhk.png',
    cover: '/food/food-pollo-brasa-mitad.png',
    address: 'Calle Bolívar, Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Pollos', 'Combos', 'Bebidas'],
  },
  {
    id: 'julieta',
    name: 'Julieta Books & Coffee',
    rating: 4.6,
    reviews: 89,
    time: '20-30 min',
    shipping: 1.0,
    type: ['Cafes', 'Restaurantes'],
    distance: '0.9 km',
    destacado: false,
    logo: '/logos/julieta.png',
    cover: '/food/food-cafe-leche.png',
    address: 'Av. Rocafuerte, Piñas',
    minOrder: 3,
    categories: ['Más pedidos', 'Cafés', 'Sandwiches', 'Postres'],
  },
  {
    id: 'mulano',
    name: 'Mulano Coffee Shop',
    rating: 4.7,
    reviews: 124,
    time: '15-25 min',
    shipping: 1.0,
    type: ['Cafes', 'Restaurantes'],
    distance: '0.7 km',
    destacado: false,
    logo: '/logos/mulano.png',
    cover: '/food/food-frappe-caramelo.png',
    address: 'Centro Comercial Piñas',
    minOrder: 3,
    categories: ['Más pedidos', 'Cafés calientes', 'Frappés', 'Postres'],
  },
  {
    id: 'lunaria',
    name: 'Lunaria Specialty Coffee',
    rating: 4.8,
    reviews: 98,
    time: '20-30 min',
    shipping: 1.5,
    type: ['Cafes', 'Restaurantes'],
    distance: '1.0 km',
    destacado: false,
    logo: '/logos/lunaria.png',
    cover: '/food/food-cold-brew.png',
    address: 'Parque Central, Piñas',
    minOrder: 3,
    categories: ['Más pedidos', 'Specialty', 'Frappés', 'Postres'],
  },
  {
    id: 'farmacia-mia',
    name: 'Farmacia Mia',
    rating: 4.7,
    reviews: 156,
    time: '15-25 min',
    shipping: 0.75,
    type: ['Farmacias'],
    distance: '0.6 km',
    destacado: false,
    logo: '/logos/farmacia-mia.png',
    cover: '/food/food-farmacia-items.png',
    address: 'Calle Sucre, Piñas',
    minOrder: 2,
    categories: ['Más pedidos', 'Analgésicos', 'Vitaminas', 'Primeros auxilios'],
  },
  {
    id: 'gran-ideal',
    name: 'Supermercado Gran Ideal',
    rating: 4.5,
    reviews: 312,
    time: '20-30 min',
    shipping: 1.0,
    type: ['Market'],
    distance: '1.1 km',
    destacado: false,
    logo: '/logos/gran-ideal.png',
    cover: '/food/food-despensa-basica.png',
    address: 'Calle Principal, Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Despensa', 'Limpieza', 'Combos'],
  },
  {
    id: 'grill51',
    name: 'Grill 51 Fast Food',
    rating: 4.6,
    reviews: 85,
    time: '20-30 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '0.9 km',
    destacado: false,
    logo: '/logos/grill51.png',
    cover: '/food/food-combo-familiar.png',
    address: 'Calle 9 de Octubre, Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Combos', 'Hamburguesas', 'Bebidas'],
  },
  {
    id: 'don-bolo',
    name: 'Don Bolo Marisquería',
    rating: 4.7,
    reviews: 92,
    time: '25-35 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '1.0 km',
    destacado: false,
    logo: '/logos/Don_Bolo.png',
    cover: '/food/food-despensa-basica.png',
    address: 'Av. Rocafuerte, Piñas',
    minOrder: 8,
    categories: ['Más pedidos', 'Ceviches', 'Mariscos', 'Bebidas'],
  },
  {
    id: 'garua',
    name: 'Garúa · Sabores de Antaño',
    rating: 4.8,
    reviews: 76,
    time: '20-30 min',
    shipping: 1.0,
    type: ['Restaurantes', 'Cafes'],
    distance: '0.8 km',
    destacado: true,
    logo: '/logos/garua.png',
    cover: '/food/food-cafe-leche.png',
    address: 'Piñas, El Oro',
    minOrder: 5,
    categories: ['Más pedidos', 'Tradicional', 'Bebidas', 'Postres'],
  },
  {
    id: 'stop-asadero',
    name: 'Stop Asadero Aquí',
    rating: 4.5,
    reviews: 68,
    time: '25-35 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '1.2 km',
    destacado: false,
    logo: '/logos/stop.png',
    cover: '/food/food-pollo-brasa-mitad.png',
    address: 'Calle Sucre, Piñas',
    minOrder: 6,
    categories: ['Más pedidos', 'Asados', 'Combos', 'Bebidas'],
  },
  {
    id: 'chifa-integral',
    name: 'Chifa Integral',
    rating: 4.6,
    reviews: 134,
    time: '20-30 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '0.9 km',
    destacado: false,
    logo: '/logos/chifa_Integral.png',
    cover: '/food/food-sandwich-club.png',
    address: 'Av. 9 de Octubre, Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Arroz', 'Tallarines', 'Sopas', 'Bebidas'],
  },
  {
    id: 'gorilla-food',
    name: 'Gorilla Food',
    rating: 4.5,
    reviews: 88,
    time: '18-28 min',
    shipping: 1.0,
    type: ['Restaurantes'],
    distance: '0.7 km',
    destacado: false,
    logo: '/logos/Gorila.png',
    cover: '/food/food-combo-familiar.png',
    address: 'Centro Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Hamburguesas', 'Combos', 'Bebidas'],
  },
  {
    id: 'santa-ana',
    name: 'Santa Ana',
    rating: 4.6,
    reviews: 54,
    time: '22-32 min',
    shipping: 1.0,
    type: ['Restaurantes'],
    distance: '1.1 km',
    destacado: false,
    logo: '/logos/santa_ana.png',
    cover: '/food/food-torta-chocolate.png',
    address: 'Sector Santa Ana, Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Platos', 'Bebidas', 'Postres'],
  },
  {
    id: 'jose-maria-taqueria',
    name: 'José María La Taquería',
    rating: 4.7,
    reviews: 112,
    time: '20-30 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '0.8 km',
    destacado: false,
    logo: '/logos/jose_maria_taqueria.png',
    cover: '/food/food-sandwich-club.png',
    address: 'Calle Bolívar, Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Tacos', 'Burritos', 'Bebidas'],
  },
  {
    id: 'el-coral',
    name: 'EL Coral Picantería',
    rating: 4.7,
    reviews: 95,
    time: '25-35 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '1.0 km',
    destacado: false,
    logo: '/logos/El_coral.png',
    cover: '/food/food-despensa-basica.png',
    address: 'Av. Los Ceibos, Piñas',
    minOrder: 8,
    categories: ['Más pedidos', 'Mariscos', 'Picantes', 'Bebidas'],
  },
  {
    id: 'pineapple-skull',
    name: 'Pineapple Skull · Piñas 18',
    rating: 4.5,
    reviews: 62,
    time: '20-30 min',
    shipping: 1.0,
    type: ['Restaurantes', 'Cafes'],
    distance: '0.9 km',
    destacado: false,
    logo: '/logos/Pineaple.png',
    cover: '/food/food-frappe-caramelo.png',
    address: 'Piñas, El Oro',
    minOrder: 5,
    categories: ['Más pedidos', 'Combos', 'Bebidas', 'Snacks'],
  },
  {
    id: 'pichanas',
    name: 'Pichanas Restaurante',
    rating: 4.8,
    reviews: 118,
    time: '25-35 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '1.1 km',
    destacado: true,
    logo: '/logos/pichanas.png',
    cover: '/food/food-pollo-entero.png',
    address: 'Calle Principal, Piñas',
    minOrder: 6,
    categories: ['Más pedidos', 'Carnes', 'Platos típicos', 'Bebidas'],
  },
  {
    id: 'taberna-real',
    name: 'Taberna Real Restaurante',
    rating: 4.6,
    reviews: 87,
    time: '22-32 min',
    shipping: 1.5,
    type: ['Restaurantes'],
    distance: '1.0 km',
    destacado: false,
    logo: '/logos/taberna_real.png',
    cover: '/food/food-combo-familiar.png',
    address: 'Parque Central, Piñas',
    minOrder: 6,
    categories: ['Más pedidos', 'Platos', 'Bebidas', 'Postres'],
  },
  {
    id: 'montanita',
    name: 'Montañita Restaurante',
    rating: 4.7,
    reviews: 71,
    time: '20-30 min',
    shipping: 1.0,
    type: ['Restaurantes'],
    distance: '0.8 km',
    destacado: false,
    logo: '/logos/montanita.png',
    cover: '/food/food-pollo-brasa-mitad.png',
    address: 'Sector Montañita, Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Platos', 'Almuerzos', 'Bebidas'],
  },
  {
    id: 'dejame-que-te-cuente',
    name: 'Déjame que te Cuente!',
    rating: 4.6,
    reviews: 83,
    time: '22-32 min',
    shipping: 1.0,
    type: ['Restaurantes'],
    distance: '0.9 km',
    destacado: false,
    logo: '/logos/dejame_que_te_cuente.png',
    cover: '/food/food-brownie-cafe.png',
    address: 'Av. Rocafuerte, Piñas',
    minOrder: 5,
    categories: ['Más pedidos', 'Platos', 'Bebidas', 'Postres'],
  },
];

export const MENUS: Record<string, MenuItem[]> = {
  rhk: [
    {
      id: 'rhk-1',
      name: 'Pollo a la brasa (1/2)',
      price: 8.5,
      description: 'Con papas y ensalada fresca',
      image: '/food/food-pollo-brasa-mitad.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'rhk-1b',
      name: 'Pollo a la brasa (1/2)',
      price: 8.5,
      description: 'Con papas y ensalada fresca',
      image: '/food/food-pollo-brasa-mitad.png',
      bestseller: true,
      category: 'Pollos',
    },
    {
      id: 'rhk-2',
      name: 'Pollo entero',
      price: 14,
      description: 'Asado a la leña, dorado y jugoso',
      image: '/food/food-pollo-entero.png',
      category: 'Pollos',
    },
    {
      id: 'rhk-3',
      name: 'Combo familiar',
      price: 22,
      description: 'Pollo + papas grandes + gaseosa 2L',
      image: '/food/food-combo-familiar.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'rhk-3b',
      name: 'Combo familiar',
      price: 22,
      description: 'Pollo + papas grandes + gaseosa 2L',
      image: '/food/food-combo-familiar.png',
      bestseller: true,
      category: 'Combos',
    },
    {
      id: 'rhk-4',
      name: 'Combo dúo',
      price: 14,
      description: '2 presas + papas + bebida',
      image: '/food/food-combo-familiar.png',
      category: 'Combos',
    },
    {
      id: 'rhk-5',
      name: 'Gaseosa 2L',
      price: 2.5,
      description: 'Coca-Cola, Sprite o Fanta',
      image: '/food/food-pollo-brasa-mitad.png',
      category: 'Bebidas',
    },
  ],
  julieta: [
    {
      id: 'julieta-1',
      name: 'Café con leche',
      price: 2.5,
      description: 'Café recién pasado con leche cremosa',
      image: '/food/food-cafe-leche.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'julieta-1b',
      name: 'Café con leche',
      price: 2.5,
      description: 'Café recién pasado con leche cremosa',
      image: '/food/food-cafe-leche.png',
      bestseller: true,
      category: 'Cafés',
    },
    {
      id: 'julieta-2',
      name: 'Sandwich club',
      price: 5.5,
      description: 'Pollo, tocino y aguacate',
      image: '/food/food-sandwich-club.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'julieta-2b',
      name: 'Sandwich club',
      price: 5.5,
      description: 'Pollo, tocino y aguacate',
      image: '/food/food-sandwich-club.png',
      bestseller: true,
      category: 'Sandwiches',
    },
    {
      id: 'julieta-3',
      name: 'Torta de chocolate',
      price: 4,
      description: 'Con ganache y virutas de cacao',
      image: '/food/food-torta-chocolate.png',
      category: 'Postres',
    },
    {
      id: 'julieta-4',
      name: 'Brownie con café',
      price: 4.5,
      description: 'Brownie fudgy con salsa de café',
      image: '/food/food-brownie-cafe.png',
      category: 'Postres',
    },
    {
      id: 'julieta-5',
      name: 'Americano',
      price: 2.0,
      description: 'Espresso largo, suave y aromático',
      image: '/food/food-cafe-leche.png',
      category: 'Cafés',
    },
  ],
  mulano: [
    {
      id: 'mulano-1',
      name: 'Café con leche',
      price: 2.5,
      description: 'Blend especial de origen',
      image: '/food/food-cafe-leche.png',
      category: 'Cafés calientes',
    },
    {
      id: 'mulano-2',
      name: 'Frappé de caramelo',
      price: 4.5,
      description: 'Frío, cremoso y con caramelo',
      image: '/food/food-frappe-caramelo.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'mulano-2b',
      name: 'Frappé de caramelo',
      price: 4.5,
      description: 'Frío, cremoso y con caramelo',
      image: '/food/food-frappe-caramelo.png',
      bestseller: true,
      category: 'Frappés',
    },
    {
      id: 'mulano-3',
      name: 'Flat white',
      price: 3.5,
      description: 'Doble espresso con leche vaporizada',
      image: '/food/food-flat-white.png',
      category: 'Más pedidos',
    },
    {
      id: 'mulano-3b',
      name: 'Flat white',
      price: 3.5,
      description: 'Doble espresso con leche vaporizada',
      image: '/food/food-flat-white.png',
      category: 'Cafés calientes',
    },
    {
      id: 'mulano-4',
      name: 'Torta de chocolate',
      price: 4,
      description: 'Receta de la casa',
      image: '/food/food-torta-chocolate.png',
      category: 'Postres',
    },
    {
      id: 'mulano-5',
      name: 'Frappé de vainilla',
      price: 4.5,
      description: 'Con extracto de vainilla real y crema',
      image: '/food/food-frappe-caramelo.png',
      category: 'Frappés',
    },
  ],
  lunaria: [
    {
      id: 'lunaria-1',
      name: 'Cold brew',
      price: 3.5,
      description: 'Café especial macerado 18h en frío',
      image: '/food/food-cold-brew.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'lunaria-1b',
      name: 'Cold brew',
      price: 3.5,
      description: 'Café especial macerado 18h en frío',
      image: '/food/food-cold-brew.png',
      bestseller: true,
      category: 'Specialty',
    },
    {
      id: 'lunaria-2',
      name: 'Flat white',
      price: 4,
      description: 'Specialty coffee con microfoam',
      image: '/food/food-flat-white.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'lunaria-2b',
      name: 'Flat white',
      price: 4,
      description: 'Specialty coffee con microfoam',
      image: '/food/food-flat-white.png',
      bestseller: true,
      category: 'Specialty',
    },
    {
      id: 'lunaria-3',
      name: 'Frappé de caramelo',
      price: 4.5,
      description: 'Con crema chantilly y caramelo',
      image: '/food/food-frappe-caramelo.png',
      category: 'Frappés',
    },
    {
      id: 'lunaria-4',
      name: 'Brownie artesanal',
      price: 3.5,
      description: 'Horneado diario, con café',
      image: '/food/food-brownie-cafe.png',
      category: 'Postres',
    },
    {
      id: 'lunaria-5',
      name: 'Frappé de chocolate',
      price: 4.5,
      description: 'Chocolate belga, crema y cacao en polvo',
      image: '/food/food-frappe-caramelo.png',
      category: 'Frappés',
    },
  ],
  'farmacia-mia': [
    {
      id: 'farmacia-1',
      name: 'Paracetamol 500mg',
      price: 2.5,
      description: 'Caja x50 tabletas',
      image: '/food/food-farmacia-items.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'farmacia-1b',
      name: 'Paracetamol 500mg',
      price: 2.5,
      description: 'Caja x50 tabletas',
      image: '/food/food-farmacia-items.png',
      bestseller: true,
      category: 'Analgésicos',
    },
    {
      id: 'farmacia-2',
      name: 'Vitamina C 500mg',
      price: 4,
      description: 'Frasco x30 tabletas',
      image: '/food/food-farmacia-items.png',
      category: 'Más pedidos',
    },
    {
      id: 'farmacia-2b',
      name: 'Vitamina C 500mg',
      price: 4,
      description: 'Frasco x30 tabletas',
      image: '/food/food-farmacia-items.png',
      category: 'Vitaminas',
    },
    {
      id: 'farmacia-3',
      name: 'Alcohol antiséptico',
      price: 1.5,
      description: '400ml · 70%',
      image: '/food/food-farmacia-items.png',
      category: 'Primeros auxilios',
    },
    {
      id: 'farmacia-4',
      name: 'Termómetro digital',
      price: 5,
      description: 'Lectura rápida en segundos',
      image: '/food/food-farmacia-items.png',
      category: 'Primeros auxilios',
    },
    {
      id: 'farmacia-5',
      name: 'Ibuprofeno 400mg',
      price: 3.0,
      description: 'Caja x20 tabletas · Antiinflamatorio',
      image: '/food/food-farmacia-items.png',
      category: 'Analgésicos',
    },
  ],
  'gran-ideal': [
    {
      id: 'gran-1',
      name: 'Despensa básica',
      price: 15,
      description: 'Arroz, aceite, azúcar · Canasta familiar',
      image: '/food/food-despensa-basica.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'gran-1b',
      name: 'Despensa básica',
      price: 15,
      description: 'Arroz, aceite, azúcar · Canasta familiar',
      image: '/food/food-despensa-basica.png',
      bestseller: true,
      category: 'Despensa',
    },
    {
      id: 'gran-2',
      name: 'Abarrotes esenciales',
      price: 25,
      description: 'Surtido mensual para el hogar',
      image: '/food/food-despensa-basica.png',
      category: 'Despensa',
    },
    {
      id: 'gran-3',
      name: 'Productos de limpieza',
      price: 12,
      description: 'Detergente, desinfectante y más',
      image: '/food/food-despensa-basica.png',
      category: 'Limpieza',
    },
    {
      id: 'gran-4',
      name: 'Combo ahorro',
      price: 20,
      description: 'Fácil de comprar, fácil de ahorrar',
      image: '/food/food-despensa-basica.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'gran-4b',
      name: 'Combo ahorro',
      price: 20,
      description: 'Fácil de comprar, fácil de ahorrar',
      image: '/food/food-despensa-basica.png',
      bestseller: true,
      category: 'Combos',
    },
    {
      id: 'gran-5',
      name: 'Combo hogar completo',
      price: 35,
      description: 'Despensa + limpieza para un mes',
      image: '/food/food-despensa-basica.png',
      category: 'Combos',
    },
  ],
  grill51: [
    {
      id: 'grill51-1',
      name: 'Combo BBQ Smoke',
      price: 8.5,
      description: 'Hamburguesa BBQ + papas + gaseosa',
      image: '/food/food-combo-familiar.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'grill51-1b',
      name: 'Combo BBQ Smoke',
      price: 8.5,
      description: 'Hamburguesa BBQ + papas + gaseosa',
      image: '/food/food-combo-familiar.png',
      bestseller: true,
      category: 'Combos',
    },
    {
      id: 'grill51-2',
      name: 'Hamburguesa Grill Classic',
      price: 5.5,
      description: 'Carne a la parrilla, queso, lechuga y salsa especial',
      image: '/food/food-sandwich-club.png',
      bestseller: true,
      category: 'Más pedidos',
    },
    {
      id: 'grill51-2b',
      name: 'Hamburguesa Grill Classic',
      price: 5.5,
      description: 'Carne a la parrilla, queso, lechuga y salsa especial',
      image: '/food/food-sandwich-club.png',
      bestseller: true,
      category: 'Hamburguesas',
    },
    {
      id: 'grill51-3',
      name: 'Combo Clásico x2',
      price: 14,
      description: '2 hamburguesas + papas grandes + 2 gaseosas',
      image: '/food/food-combo-familiar.png',
      category: 'Combos',
    },
    {
      id: 'grill51-4',
      name: 'Gaseosa 500ml',
      price: 1.25,
      description: 'Coca-Cola, Sprite o Fanta',
      image: '/food/food-pollo-brasa-mitad.png',
      category: 'Bebidas',
    },
    {
      id: 'grill51-5',
      name: 'Limonada natural',
      price: 2.0,
      description: 'Fresca y natural',
      image: '/food/food-pollo-brasa-mitad.png',
      category: 'Bebidas',
    },
  ],
  'don-bolo': [
    { id: 'don-bolo-1', name: 'Ceviche mixto', price: 12, description: 'Pescado, camarón y pulpo', image: '/food/food-despensa-basica.png', bestseller: true, category: 'Más pedidos' },
    { id: 'don-bolo-2', name: 'Arroz con menestra y camarones', price: 9.5, description: 'Porción generosa', image: '/food/food-despensa-basica.png', category: 'Mariscos' },
    { id: 'don-bolo-3', name: 'Camarones al ajillo', price: 14, description: 'Con arroz blanco', image: '/food/food-despensa-basica.png', bestseller: true, category: 'Mariscos' },
    { id: 'don-bolo-4', name: 'Encebollado', price: 5.5, description: 'Sopa de pescado tradicional', image: '/food/food-despensa-basica.png', category: 'Ceviches' },
    { id: 'don-bolo-5', name: 'Limonada', price: 2, description: 'Natural o con hierbabuena', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
  ],
  garua: [
    { id: 'garua-1', name: 'Seco de pollo', price: 6.5, description: 'Sabores de antaño', image: '/food/food-cafe-leche.png', bestseller: true, category: 'Más pedidos' },
    { id: 'garua-2', name: 'Café con leche', price: 2.5, description: 'Tradicional', image: '/food/food-cafe-leche.png', category: 'Bebidas' },
    { id: 'garua-3', name: 'Arroz con menestra y carne', price: 5.5, description: 'Plato del día', image: '/food/food-cafe-leche.png', category: 'Tradicional' },
    { id: 'garua-4', name: 'Torta de banano', price: 3.5, description: 'Casera', image: '/food/food-torta-chocolate.png', category: 'Postres' },
  ],
  'stop-asadero': [
    { id: 'stop-1', name: 'Pollo a la brasa (1/2)', price: 8, description: 'Asado aquí', image: '/food/food-pollo-brasa-mitad.png', bestseller: true, category: 'Más pedidos' },
    { id: 'stop-2', name: 'Combo familiar', price: 20, description: 'Pollo + papas + gaseosa', image: '/food/food-combo-familiar.png', category: 'Combos' },
    { id: 'stop-3', name: 'Chorizo con papas', price: 5, description: 'Porción', image: '/food/food-pollo-brasa-mitad.png', category: 'Asados' },
    { id: 'stop-4', name: 'Gaseosa 1.5L', price: 2, description: 'Varias marcas', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
  ],
  'chifa-integral': [
    { id: 'chifa-1', name: 'Arroz cantonés', price: 5.5, description: 'Con vegetales y huevo', image: '/food/food-sandwich-club.png', bestseller: true, category: 'Más pedidos' },
    { id: 'chifa-2', name: 'Tallarín saltado', price: 6, description: 'Carne o pollo', image: '/food/food-sandwich-club.png', category: 'Tallarines' },
    { id: 'chifa-3', name: 'Sopa wantán', price: 4, description: '4 unidades', image: '/food/food-sandwich-club.png', category: 'Sopas' },
    { id: 'chifa-4', name: 'Chaulafan mixto', price: 7, description: 'Arroz frito integral', image: '/food/food-sandwich-club.png', bestseller: true, category: 'Arroz' },
    { id: 'chifa-5', name: 'Té helado', price: 1.5, description: 'Limonada o durazno', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
  ],
  'gorilla-food': [
    { id: 'gorilla-1', name: 'Gorilla Burger', price: 6.5, description: 'Doble carne, queso, bacon', image: '/food/food-combo-familiar.png', bestseller: true, category: 'Más pedidos' },
    { id: 'gorilla-2', name: 'Combo Gorilla', price: 9, description: 'Hamburguesa + papas + bebida', image: '/food/food-combo-familiar.png', category: 'Combos' },
    { id: 'gorilla-3', name: 'Papas fritas', price: 2.5, description: 'Porción grande', image: '/food/food-combo-familiar.png', category: 'Combos' },
    { id: 'gorilla-4', name: 'Gaseosa', price: 1.25, description: '500ml', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
  ],
  'santa-ana': [
    { id: 'santa-1', name: 'Almuerzo ejecutivo', price: 5.5, description: 'Sopa + seco + jugo', image: '/food/food-torta-chocolate.png', bestseller: true, category: 'Más pedidos' },
    { id: 'santa-2', name: 'Seco de res', price: 6, description: 'Con arroz y menestra', image: '/food/food-torta-chocolate.png', category: 'Platos' },
    { id: 'santa-3', name: 'Jugo natural', price: 2, description: 'Variedad de frutas', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
    { id: 'santa-4', name: 'Postre del día', price: 3, description: 'Casero', image: '/food/food-torta-chocolate.png', category: 'Postres' },
  ],
  'jose-maria-taqueria': [
    { id: 'jose-1', name: 'Tacos al pastor x3', price: 5.5, description: 'Cebolla, cilantro, limón', image: '/food/food-sandwich-club.png', bestseller: true, category: 'Más pedidos' },
    { id: 'jose-2', name: 'Burrito de res', price: 6.5, description: 'Grande, con guacamole', image: '/food/food-sandwich-club.png', category: 'Burritos' },
    { id: 'jose-3', name: 'Quesadilla', price: 4.5, description: 'Con queso y pollo', image: '/food/food-sandwich-club.png', category: 'Tacos' },
    { id: 'jose-4', name: 'Horchata', price: 2, description: 'Arroz con canela', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
  ],
  'el-coral': [
    { id: 'coral-1', name: 'Ceviche de concha', price: 10, description: 'Picante al gusto', image: '/food/food-despensa-basica.png', bestseller: true, category: 'Más pedidos' },
    { id: 'coral-2', name: 'Arroz con mariscos', price: 11, description: 'Picantería style', image: '/food/food-despensa-basica.png', category: 'Mariscos' },
    { id: 'coral-3', name: 'Sudado de pescado', price: 9.5, description: 'Con yuca y maduro', image: '/food/food-despensa-basica.png', category: 'Picantes' },
    { id: 'coral-4', name: 'Chicha', price: 1.5, description: 'De piña o mora', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
  ],
  'pineapple-skull': [
    { id: 'pskull-1', name: 'Combo Piñas 18', price: 8, description: 'Hamburguesa + papas + bebida', image: '/food/food-frappe-caramelo.png', bestseller: true, category: 'Más pedidos' },
    { id: 'pskull-2', name: 'Frappé', price: 4, description: 'Varios sabores', image: '/food/food-frappe-caramelo.png', category: 'Bebidas' },
    { id: 'pskull-3', name: 'Snack pack', price: 3.5, description: 'Papas + nuggets', image: '/food/food-frappe-caramelo.png', category: 'Snacks' },
  ],
  pichanas: [
    { id: 'pichanas-1', name: 'Churrasco', price: 9, description: 'Con huevo, maduro y ensalada', image: '/food/food-pollo-entero.png', bestseller: true, category: 'Más pedidos' },
    { id: 'pichanas-2', name: 'Seco de chivo', price: 8.5, description: 'Plato típico', image: '/food/food-pollo-entero.png', category: 'Platos típicos' },
    { id: 'pichanas-3', name: 'Bandeja montañera', price: 10, description: 'Arroz, huevo, chorizo, maduro', image: '/food/food-pollo-entero.png', category: 'Carnes' },
    { id: 'pichanas-4', name: 'Limonada', price: 2, description: 'Natural', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
  ],
  'taberna-real': [
    { id: 'taberna-1', name: 'Plato del día', price: 6.5, description: 'Sopa + segundo + postre', image: '/food/food-combo-familiar.png', bestseller: true, category: 'Más pedidos' },
    { id: 'taberna-2', name: 'Costillas BBQ', price: 11, description: 'Porción real', image: '/food/food-combo-familiar.png', category: 'Platos' },
    { id: 'taberna-3', name: 'Cerveza artesanal', price: 4, description: 'Varias opciones', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
    { id: 'taberna-4', name: 'Brownie', price: 3.5, description: 'Con helado', image: '/food/food-brownie-cafe.png', category: 'Postres' },
  ],
  montanita: [
    { id: 'montanita-1', name: 'Almuerzo montañita', price: 5.5, description: 'Casero y abundante', image: '/food/food-pollo-brasa-mitad.png', bestseller: true, category: 'Más pedidos' },
    { id: 'montanita-2', name: 'Seco de pollo', price: 5, description: 'Con arroz y menestra', image: '/food/food-pollo-brasa-mitad.png', category: 'Almuerzos' },
    { id: 'montanita-3', name: 'Caldo de gallina', price: 4.5, description: 'Reconstituyente', image: '/food/food-pollo-brasa-mitad.png', category: 'Platos' },
    { id: 'montanita-4', name: 'Jugo natural', price: 2, description: 'Del día', image: '/food/food-pollo-brasa-mitad.png', category: 'Bebidas' },
  ],
  'dejame-que-te-cuente': [
    { id: 'dejame-1', name: 'Menú ejecutivo', price: 6, description: 'Sopa + segundo + bebida', image: '/food/food-brownie-cafe.png', bestseller: true, category: 'Más pedidos' },
    { id: 'dejame-2', name: 'Lasagna', price: 7, description: 'Casa', image: '/food/food-brownie-cafe.png', category: 'Platos' },
    { id: 'dejame-3', name: 'Café', price: 2.5, description: 'Expreso o con leche', image: '/food/food-cafe-leche.png', category: 'Bebidas' },
    { id: 'dejame-4', name: 'Tiramisú', price: 4.5, description: 'Casero', image: '/food/food-brownie-cafe.png', category: 'Postres' },
  ],
};

export const REVIEWS: Record<string, Review[]> = {
  rhk: [
    { author: 'María G.', rating: 5, comment: '¡El mejor pollo a la brasa de Piñas! Siempre lo pido con papas y llega caliente.' },
    { author: 'Carlos V.', rating: 5, comment: 'El combo familiar es increíble. Suficiente para toda la familia y a muy buen precio.' },
    { author: 'Andrea P.', rating: 4, comment: 'Muy rico y llegó rápido. El socio muy amable. Lo recomiendo.' },
  ],
  julieta: [
    { author: 'Jean M.', rating: 5, comment: 'El ambiente reflejado en la comida. El brownie con café es simplemente perfecto.' },
    { author: 'Valeria T.', rating: 5, comment: 'El sandwich club es el mejor que he probado en Piñas. El café es delicioso.' },
    { author: 'Sofía R.', rating: 4, comment: 'Lugar encantador. La torta de chocolate es imperdible.' },
  ],
  mulano: [
    { author: 'Diego L.', rating: 5, comment: 'El frappé de caramelo es adictivo. Siempre lo pido cuando trabajo desde casa.' },
    { author: 'Camila N.', rating: 5, comment: 'El flat white perfectamente preparado. Se nota que usan café de calidad.' },
    { author: 'Luis F.', rating: 4, comment: 'Muy buen café y llegó bien empacado. Volvería a pedir sin duda.' },
  ],
  lunaria: [
    { author: 'Isabela M.', rating: 5, comment: 'El cold brew es una experiencia diferente. No hay otro igual en la zona.' },
    { author: 'Roberto C.', rating: 5, comment: 'Specialty coffee de verdad. Se nota el cuidado en cada preparación.' },
    { author: 'Paola S.', rating: 5, comment: 'El flat white y el brownie artesanal son mi combinación favorita. 100% recomendado.' },
  ],
  'farmacia-mia': [
    { author: 'Elena R.', rating: 5, comment: 'Rapidísimo. Pedí el paracetamol y llegó en menos de 20 minutos. Excelente servicio.' },
    { author: 'Miguel A.', rating: 4, comment: 'Buena variedad de productos. El termómetro digital llegó bien empacado.' },
    { author: 'Rosa T.', rating: 5, comment: 'Muy útil para emergencias. Precios justos y entrega confiable.' },
  ],
  'gran-ideal': [
    { author: 'Patricia L.', rating: 5, comment: 'La despensa básica es perfecta. Ahorra mucho tiempo y viene bien empacada.' },
    { author: 'Fernando G.', rating: 4, comment: 'El combo ahorro vale muchísimo la pena. Buenos precios y entrega puntual.' },
    { author: 'Mónica H.', rating: 5, comment: 'Fácil de pedir y siempre completo. El Gran Ideal en delivery es un acierto.' },
  ],
  grill51: [
    { author: 'Luis M.', rating: 5, comment: 'El Combo BBQ Smoke es increíble. Siempre llega caliente y bien empacado.' },
    { author: 'Valeria C.', rating: 5, comment: 'Las mejores hamburguesas de Piñas. El Combo Clásico es mi favorito.' },
    { author: 'Ana T.', rating: 4, comment: 'Muy buen servicio y entrega rápida. La Grill Classic es deliciosa.' },
  ],
  'don-bolo': [
    { author: 'Carmen P.', rating: 5, comment: 'El ceviche mixto es fresco y abundante. Don Bolo no defrauda.' },
    { author: 'Ricardo M.', rating: 4, comment: 'Buenos mariscos y atención. Recomiendo los camarones al ajillo.' },
  ],
  garua: [
    { author: 'Lucía F.', rating: 5, comment: 'Sabores de antaño de verdad. El seco y el café son mi debilidad.' },
    { author: 'Oscar R.', rating: 5, comment: 'Garúa es un clásico de Piñas. Siempre bien atendido.' },
  ],
  'stop-asadero': [
    { author: 'Fernando G.', rating: 4, comment: 'Pollo rico y buen precio. Llega caliente.' },
    { author: 'Diana S.', rating: 5, comment: 'El combo familiar es ideal para compartir. Muy recomendado.' },
  ],
  'chifa-integral': [
    { author: 'Patricia L.', rating: 5, comment: 'El mejor chifa de Piñas. Arroz cantonés y tallarín siempre perfectos.' },
    { author: 'Roberto C.', rating: 4, comment: 'Chaulafan integral muy bueno. Entrega puntual.' },
  ],
  'gorilla-food': [
    { author: 'Miguel A.', rating: 5, comment: 'La Gorilla Burger es bestial. Me encanta.' },
    { author: 'Sandra T.', rating: 4, comment: 'Combos bien servidos y ricos. Buenas papas.' },
  ],
  'santa-ana': [
    { author: 'Elena R.', rating: 5, comment: 'Almuerzo ejecutivo muy completo. Santa Ana es una joya.' },
    { author: 'Andrés P.', rating: 4, comment: 'Buen trato y platos caseros. Volveré.' },
  ],
  'jose-maria-taqueria': [
    { author: 'Valeria M.', rating: 5, comment: 'Los tacos al pastor son auténticos. José María es mi taquería favorita.' },
    { author: 'Luis F.', rating: 5, comment: 'Burritos enormes y horchata deliciosa. 100% recomendado.' },
  ],
  'el-coral': [
    { author: 'María G.', rating: 5, comment: 'Ceviche de concha picante como me gusta. El Coral es único.' },
    { author: 'Carlos V.', rating: 4, comment: 'Sudado de pescado muy sabroso. Buena picantería.' },
  ],
  'pineapple-skull': [
    { author: 'Jean M.', rating: 4, comment: 'Combo Piñas 18 está bueno. Ambiente diferente.' },
    { author: 'Paola S.', rating: 5, comment: 'Los frappés y el concepto me encantan. Muy Piñas.' },
  ],
  pichanas: [
    { author: 'Diego L.', rating: 5, comment: 'El churrasco de Pichanas es de otro nivel. Restaurante con sello.' },
    { author: 'Camila N.', rating: 5, comment: 'Seco de chivo y bandeja montañera increíbles. Siempre pido aquí.' },
  ],
  'taberna-real': [
    { author: 'Isabela M.', rating: 5, comment: 'Taberna Real tiene ambiente y buena comida. Las costillas BBQ excelentes.' },
    { author: 'Roberto C.', rating: 4, comment: 'Plato del día muy bien presentado. Buen servicio.' },
  ],
  montanita: [
    { author: 'Rosa T.', rating: 5, comment: 'Almuerzo montañita casero y abundante. Montañita Restaurante no falla.' },
    { author: 'Fernando G.', rating: 4, comment: 'Caldo de gallina perfecto para el frío. Recomendado.' },
  ],
  'dejame-que-te-cuente': [
    { author: 'Andrea P.', rating: 5, comment: 'Menú ejecutivo muy completo. Déjame que te Cuente es un must.' },
    { author: 'Sofía R.', rating: 4, comment: 'Lasagna y tiramisú deliciosos. Buen lugar para comer.' },
  ],
};
